name: Build Aether Weave Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install and Build
        run: |
          # Install Android SDK Command-line tools
          sudo apt-get update
          sudo apt-get install -y android-sdk

          # Accept licenses and install required packages
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-32" "build-tools;32.0.0"

          # Install Cordova and plugins, then build
          npm install -g cordova
          cordova platform add android@11
          cordova plugin add cordova-plugin-androidx-adapter
          cordova plugin add cordova-plugin-admob-free --variable ADMOB_APP_ID="ca-app-pub-6989088248302599~8993141386"
          cordova build android --debug

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aether-weave-apk
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
